package Task_3_2.RecordBook;

public class SubjectsDatabase {
    public Semester[] semesters = new Semester[]{
            new Semester( new Subject[] {
                    new Subject("Введение в алгебру и анализ", 0, false),
                    new Subject("Введение в дискретную математику и математическую логику", 0, false),
                    new Subject("Декларативное программирование", 0, false),
                    new Subject("Императивное программирование", 0, false),
                    new Subject("Иностранный язык", 0, false),
                    new Subject("История", 0, true),
                    new Subject("Основы культуры речи", 0, true),
                    new Subject("Цифровые платформы", 0, false)},
                    false),
            new Semester( new Subject[] {
                    new Subject("Введение в алгебру и анализ", 0, true),
                    new Subject("Введение в дискретную математику и математическую логику", 0, true),
                    new Subject("Декларативное программирование", 0, true),
                    new Subject("Императивное программирование", 0, true),
                    new Subject("Иностранный язык", 0, false),
                    new Subject("Цифровые платформы", 0, true)},
                    false),
            new Semester( new Subject[] {
                    new Subject("Введение в искусственный интеллект", 0, true),
                    new Subject("Дифференциальные уравнения и теория функций комплексного переменного", 0, true),
                    new Subject("Иностранный язык", 0, true),
                    new Subject("Модели вычислений", 0, false),
                    new Subject("Объектно-ориентированное программирование", 0, false),
                    new Subject("Операционные системы", 0, true),
                    new Subject("Разработка ПАК", 0, false),
                    new Subject("ТВ и МС", 0, true)},
                    false),
            new Semester( new Subject[] {
                    new Subject("Введение в аналоговую электронику и технику измерений", 0, true),
                    new Subject("Введение в компьютерные сети", 0, true),
                    new Subject("Деловой английский язык", 0, true),
                    new Subject("Модели вычислений", 0, true),
                    new Subject("Объектно-ориентированное программирование", 0, true),
                    new Subject("Программируемые микроконтроллеры", 0, true),
                    new Subject("Разработка ПАК", 0, true),
                    new Subject("Теория параллелизма", 0, true),
                    new Subject("Философия", 0, true)},
                    false),
            new Semester( new Subject[] {
                    new Subject("Английский язык", 0, false),
                    new Subject("Введение в разработку мобильных приложений", 0, true),
                    new Subject("Вычислительная математика", 0, true),
                    new Subject("Кибербезопасность", 0, true),
                    new Subject("Командная разработка ПАК", 0, false),
                    new Subject("Методы машинного обучения", 0, true),
                    new Subject("Модели и методы искусственного интеллекта", 0, true),
                    new Subject("Проектирование программного обеспечения", 0, true),
                    new Subject("Хранение и обработка информации", 0, true)},
                    false),
            new Semester( new Subject[] {
                    new Subject("Английский язык", 0, true),
                    new Subject("Командная разработка ПАК", 0, true),
                    new Subject("Компьютерное моделирование", 0, true),
                    new Subject("Методы глубокого обучения", 0, true),
                    new Subject("Оптимизация Java программ", 0, true),
                    new Subject("Правоведение", 0, true),
                    new Subject("Практическая информационная безопасность", 0, true),
                    new Subject("Программирование на языке Python", 0, true),
                    new Subject("Проектирование интерфейсов пользователей", 0, true)},
                    false),
            new Semester( new Subject[] {
                    new Subject("Защита информации", 0, true),
                    new Subject("Инновационная экономика и технологическое предпринимательство", 0, true),
                    new Subject("Представление знаний с помощью Semantic Web", 0, true),
                    new Subject("Распределенные алгоритмы", 0, true),
                    new Subject("Стандартизация программной документации", 0, true),
                    new Subject("Управление производственным процессом разработки программного обеспечения", 0, true),
                    new Subject("Учебная практика, ознакомительная практика", 0, true)},
                    false),
            new Semester( new Subject[] {
                    new Subject("Безопасность жизнедеятельности", 0, true),
                    new Subject("Основы риторики", 0, true),
                    new Subject("Производственная практика, научно-исследовательская работа", 0, true),
                    new Subject("Производственная практика, технологическая (проектно-технологическая) практика", 0, true),
                    new Subject("Учебно-научный семинар «Пространство проектных решений в программно-аппаратных разработках»", 0, true),
                    new Subject("Учебно-научный семинар «Пространство проектных решений в системных разработках»", 0, true),
                    new Subject("Экономика", 0, true)},
                    false)};
}
